name: Build and Push Docker Image to Docker Hub
# Action already created to build and deploy image to github, congiure Secrets in github Repository 
on: push
jobs:
  # push_to_registry:
  #   name: push docker image to hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: check repository
  #       uses: actions/checkout@v4

  #     - name: login to docker registry
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{secrets.DOCKERHUB_USERNAME}}
  #         password: ${{secrets.DOCKERHUB_PASSWORD}}

  #     - name: build and push docker image to registry
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: #sets the context tot the default directory 
  #         push: true
  #         tags: uzair102/u_repo:image_from_github_actions_v1
  
 deploy_to_ec2:
  #needs: push_to_registry
  name: deploy_to_EC2
  runs-on: ubuntu-latest
  env:
    EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    EC2_URL: ${{ secrets.EC2_URL }}
    EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  steps:
  - name: SSH to EC2 instance
    run: |
      mkdir -p ~/.ssh
      echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/App_instance_ssh.pem
      chmod 600 ~/.ssh/App_instance_ssh.pem
      ssh -o StrictHostKeyChecking=no -i ~/.ssh/App_instance_ssh.pem $EC2_USERNAME@$EC2_URL
